minecraft_version=1.21.5
fabric_loader_version=0.16.14
fabric_api_version=0.128.2+1.21.5
geckolib_version=5.1.0
fabric_api_distribution_bytes=2248994
fabric_api_distribution_sha256=a82fd00827206e911936ed1e0ceaec6eb55d061ca5d3c5d63c7f0031426d29ae
geckolib_distribution_bytes=670425
geckolib_distribution_sha256=885ef4b03cd438c7d2ec9f59bb492f3af6ba2b73aa0493afc4f80801b5a9126c
bridge_distribution_bytes=53984
bridge_distribution_sha256=ac5bfab545b723b2346aeb017b3a6ea3186a6cbced370e16097f3836b128746d
bridge_version=0.1.2
avatar_distribution_bytes=55627
avatar_distribution_sha256=fff00f66e4beab2eff1e51f253608b198f43aa0a12443fbe07f7f3fd48278872
whitelily_license_bytes=11123
whitelily_license_sha256=226d0e41f61309952c27fcc11a5140c4e735115f702ff0484ff0c25cfbbeee16
whitelily_notice_bytes=697
whitelily_notice_sha256=6323cb4b742d322d61ee47279d71d0f0de496568cf1f2f793fea104a58ab0dde
fabric_api_license_bytes=11357
fabric_api_license_sha256=b40930bbcf80744c86c46a12bc9da056641d722716c378f5659b9e555ef833e1
geckolib_license_bytes=1065
geckolib_license_sha256=5f2943625776c6126cd252652f4c57d2fb187d339a20fa065a2b7c619165a52f
component_manifest_bytes=1984
component_manifest_sha256=9f6d60d8e8f23543689d5e61e9aa6656271daf8cf4b8028bdfebb305a12eaab0
mod_version=0.1.0
maven_group=io.github.whitelily
archives_base_name=whitelily-avatar-fabric
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
